// Code generated by tools/gen-help-text.py from the frozen capture corpus.
// DO NOT EDIT. Regenerate with: python3 tools/gen-help-text.py
//
// The reference prints these two texts itself (httpie 3.2.4's argparse help for
// `--help`, and the same help for `--manual` when the system man pages are not
// available — cli/argparser.py's print_manual falls back to format_help()).
// The bytes are the recorded ones: the captures in docs/parity-captures,
// taken with stdout piped, stdin pty, TERM=xterm-256color, COLUMNS=80, which is the rendering the parity
// harness reproduces (tests/parity/driver.py).
//
// Captures (frozen corpus — neither this script nor any test writes to them):
//   HELP_TEXT    <- docs/parity-captures/help-short.out  (15179 bytes, help-short)
//                   http --help; sha256 afe5f966d4fd89163d59cdec24c11d60b4d6026dc5c95c55528dca973cf69d1c
//   MANUAL_TEXT  <- docs/parity-captures/help-manual.txt  (15190 bytes, help-manual)
//                   http --manual; sha256 e838c8c0397aed542af883cf97edf0814b8f68b8b0cfa4e52680ff2a3b01c669
//
// Both texts are written to stdout whole, exit code 0, nothing on stderr.
// The program name inside them is the literal `http` (httpie's
// cli/definition.py sets the parser's prog to that constant), so it does not
// follow argv[0] the way httpie's error messages do.
package cli

HELP_TEXT ::
	"usage:\n" +
	"    http [METHOD] URL [REQUEST_ITEM ...]\n" +
	"\n" +
	"HTTPie: modern, user-friendly command-line HTTP client for the API era. <https://httpie.io>\n" +
	"\n" +
	"Positional arguments:\n" +
	"  \n" +
	"  These arguments come after any flags and in the order they are listed here.\n" +
	"  Only URL is required.\n" +
	"\n" +
	"  METHOD\n" +
	"      The HTTP method to be used for the request (GET, POST, PUT, DELETE, ...).\n" +
	"      \n" +
	"      This argument can be omitted in which case HTTPie will use POST if there\n" +
	"      is some data to be sent, otherwise GET:\n" +
	"      \n" +
	"          $ http example.org               # => GET\n" +
	"          $ http example.org hello=world   # => POST\n" +
	"      \n" +
	"  URL\n" +
	"      The request URL. Scheme defaults to 'http://' if the URL\n" +
	"      does not include one. (You can override this with: --default-scheme=http/https)\n" +
	"      \n" +
	"      You can also use a shorthand for localhost\n" +
	"      \n" +
	"          $ http :3000                    # => http://localhost:3000\n" +
	"          $ http :/foo                    # => http://localhost/foo\n" +
	"      \n" +
	"  REQUEST_ITEM\n" +
	"      Optional key-value pairs to be included in the request. The separator used\n" +
	"      determines the type:\n" +
	"      \n" +
	"      ':' HTTP headers:\n" +
	"      \n" +
	"          Referer:https://httpie.io  Cookie:foo=bar  User-Agent:bacon/1.0\n" +
	"      \n" +
	"      '==' URL parameters to be appended to the request URI:\n" +
	"      \n" +
	"          search==httpie\n" +
	"      \n" +
	"      '=' Data fields to be serialized into a JSON object (with --json, -j)\n" +
	"          or form data (with --form, -f):\n" +
	"      \n" +
	"          name=HTTPie  language=Python  description='CLI HTTP client'\n" +
	"      \n" +
	"      ':=' Non-string JSON data fields (only with --json, -j):\n" +
	"      \n" +
	"          awesome:=true  amount:=42  colors:='[\"red\", \"green\", \"blue\"]'\n" +
	"      \n" +
	"      '@' Form file fields (only with --form or --multipart):\n" +
	"      \n" +
	"          cv@~/Documents/CV.pdf\n" +
	"          cv@'~/Documents/CV.pdf;type=application/pdf'\n" +
	"      \n" +
	"      '=@' A data field like '=', but takes a file path and embeds its content:\n" +
	"      \n" +
	"          essay=@Documents/essay.txt\n" +
	"      \n" +
	"      ':=@' A raw JSON field like ':=', but takes a file path and embeds its content:\n" +
	"      \n" +
	"          package:=@./package.json\n" +
	"      \n" +
	"      You can use a backslash to escape a colliding separator in the field name:\n" +
	"      \n" +
	"          field-name-with\\:colon=value\n" +
	"      \n" +
	"\n" +
	"Predefined content types:\n" +
	"\n" +
	"  --json, -j\n" +
	"      (default) Data items from the command line are serialized as a JSON object.\n" +
	"      The Content-Type and Accept headers are set to application/json\n" +
	"      (if not specified).\n" +
	"      \n" +
	"  --form, -f\n" +
	"      Data items from the command line are serialized as form fields.\n" +
	"      \n" +
	"      The Content-Type is set to application/x-www-form-urlencoded (if not\n" +
	"      specified). The presence of any file fields results in a\n" +
	"      multipart/form-data request.\n" +
	"      \n" +
	"  --multipart\n" +
	"      Similar to --form, but always sends a multipart/form-data request (i.e., even without files).\n" +
	"      \n" +
	"  --boundary BOUNDARY\n" +
	"      Specify a custom boundary string for multipart/form-data requests. Only has effect only together with --form.\n" +
	"      \n" +
	"  --raw RAW\n" +
	"      This option allows you to pass raw request data without extra processing\n" +
	"      (as opposed to the structured request items syntax):\n" +
	"      \n" +
	"          $ http --raw='data' pie.dev/post\n" +
	"      \n" +
	"      You can achieve the same by piping the data via stdin:\n" +
	"      \n" +
	"          $ echo data | http pie.dev/post\n" +
	"      \n" +
	"      Or have HTTPie load the raw data from a file:\n" +
	"      \n" +
	"          $ http pie.dev/post @data.txt\n" +
	"      \n" +
	"\n" +
	"Content processing options:\n" +
	"\n" +
	"  --compress, -x\n" +
	"      Content compressed (encoded) with Deflate algorithm.\n" +
	"      The Content-Encoding header is set to deflate.\n" +
	"      \n" +
	"      Compression is skipped if it appears that compression ratio is\n" +
	"      negative. Compression can be forced by repeating the argument.\n" +
	"      \n" +
	"\n" +
	"Output processing:\n" +
	"\n" +
	"  --pretty {all,colors,format,none}\n" +
	"      Controls output processing. The value can be \"none\" to not prettify\n" +
	"      the output (default for redirected output), \"all\" to apply both colors\n" +
	"      and formatting (default for terminal output), \"colors\", or \"format\".\n" +
	"      \n" +
	"  --style STYLE, -s STYLE\n" +
	"      Output coloring style (default is \"auto\"). It can be one of:\n" +
	"      \n" +
	"              abap, algol, algol_nu, arduino, auto, autumn, borland, bw,\n" +
	"          coffee, colorful, default, dracula, emacs, friendly,\n" +
	"          friendly_grayscale, fruity, github-dark, gruvbox-dark,\n" +
	"          gruvbox-light, igor, inkpot, lightbulb, lilypond, lovelace,\n" +
	"          manni, material, monokai, murphy, native, night-owl, nord,\n" +
	"          nord-darker, one-dark, paraiso-dark, paraiso-light, pastie,\n" +
	"          perldoc, pie, pie-dark, pie-light, rainbow_dash, rrt, sas,\n" +
	"          solarized, solarized-dark, solarized-light, staroffice,\n" +
	"          stata-dark, stata-light, tango, trac, vim, vs, xcode,\n" +
	"          zenburn\n" +
	"      \n" +
	"      The \"auto\" style follows your terminal's ANSI color styles.\n" +
	"      For non-auto styles to work properly, please make sure that the\n" +
	"      $TERM environment variable is set to \"xterm-256color\" or similar\n" +
	"      (e.g., via `export TERM=xterm-256color' in your ~/.bashrc).\n" +
	"      \n" +
	"  --unsorted\n" +
	"      Disables all sorting while formatting output. It is a shortcut for:\n" +
	"      \n" +
	"          --format-options=headers.sort:false,json.sort_keys:false\n" +
	"      \n" +
	"  --sorted\n" +
	"      Re-enables all sorting options while formatting output. It is a shortcut for:\n" +
	"      \n" +
	"          --format-options=headers.sort:true,json.sort_keys:true\n" +
	"      \n" +
	"  --response-charset ENCODING\n" +
	"      Override the response encoding for terminal display purposes, e.g.:\n" +
	"      \n" +
	"          --response-charset=utf8\n" +
	"          --response-charset=big5\n" +
	"      \n" +
	"  --response-mime MIME_TYPE\n" +
	"      Override the response mime type for coloring and formatting for the terminal, e.g.:\n" +
	"      \n" +
	"          --response-mime=application/json\n" +
	"          --response-mime=text/xml\n" +
	"      \n" +
	"  --format-options FORMAT_OPTIONS\n" +
	"      Controls output formatting. Only relevant when formatting is enabled\n" +
	"      through (explicit or implied) --pretty=all or --pretty=format.\n" +
	"      The following are the default options:\n" +
	"      \n" +
	"          headers.sort:true\n" +
	"          json.format:true\n" +
	"          json.indent:4\n" +
	"          json.sort_keys:true\n" +
	"          xml.format:true\n" +
	"          xml.indent:2\n" +
	"      \n" +
	"      You may use this option multiple times, as well as specify multiple\n" +
	"      comma-separated options at the same time. For example, this modifies the\n" +
	"      settings to disable the sorting of JSON keys, and sets the indent size to 2:\n" +
	"      \n" +
	"          --format-options json.sort_keys:false,json.indent:2\n" +
	"      \n" +
	"      This is something you will typically put into your config file.\n" +
	"      \n" +
	"\n" +
	"Output options:\n" +
	"\n" +
	"  --print WHAT, -p WHAT\n" +
	"      String specifying what the output should contain:\n" +
	"      \n" +
	"          'H' request headers\n" +
	"          'B' request body\n" +
	"          'h' response headers\n" +
	"          'b' response body\n" +
	"          'm' response metadata\n" +
	"      \n" +
	"      The default behaviour is 'hb' (i.e., the response\n" +
	"      headers and body is printed), if standard output is not redirected.\n" +
	"      If the output is piped to another program or to a file, then only the\n" +
	"      response body is printed by default.\n" +
	"      \n" +
	"  --headers, -h\n" +
	"      Print only the response headers. Shortcut for --print=h.\n" +
	"      \n" +
	"  --meta, -m\n" +
	"      Print only the response metadata. Shortcut for --print=m.\n" +
	"      \n" +
	"  --body, -b\n" +
	"      Print only the response body. Shortcut for --print=b.\n" +
	"      \n" +
	"  --verbose, -v\n" +
	"      Verbose output. For the level one (with single `-v`/`--verbose`), print\n" +
	"      the whole request as well as the response. Also print any intermediary\n" +
	"      requests/responses (such as redirects). For the second level and higher,\n" +
	"      print these as well as the response metadata.\n" +
	"      \n" +
	"      Level one is a shortcut for: --all --print=BHbh\n" +
	"      Level two is a shortcut for: --all --print=BHbhm\n" +
	"      \n" +
	"  --all\n" +
	"      By default, only the final request/response is shown. Use this flag to show\n" +
	"      any intermediary requests/responses as well. Intermediary requests include\n" +
	"      followed redirects (with --follow), the first unauthorized request when\n" +
	"      Digest auth is used (--auth=digest), etc.\n" +
	"      \n" +
	"  --stream, -S\n" +
	"      Always stream the response body by line, i.e., behave like `tail -f'.\n" +
	"      \n" +
	"      Without --stream and with --pretty (either set or implied),\n" +
	"      HTTPie fetches the whole response before it outputs the processed data.\n" +
	"      \n" +
	"      Set this option when you want to continuously display a prettified\n" +
	"      long-lived response, such as one from the Twitter streaming API.\n" +
	"      \n" +
	"      It is useful also without --pretty: It ensures that the output is flushed\n" +
	"      more often and in smaller chunks.\n" +
	"      \n" +
	"  --output FILE, -o FILE\n" +
	"      Save output to FILE instead of stdout. If --download is also set, then only\n" +
	"      the response body is saved to FILE. Other parts of the HTTP exchange are\n" +
	"      printed to stderr.\n" +
	"      \n" +
	"  --download, -d\n" +
	"      Do not print the response body to stdout. Rather, download it and store it\n" +
	"      in a file. The filename is guessed unless specified with --output\n" +
	"      [filename]. This action is similar to the default behaviour of wget.\n" +
	"      \n" +
	"  --continue, -c\n" +
	"      Resume an interrupted download. Note that the --output option needs to be\n" +
	"      specified as well.\n" +
	"      \n" +
	"  --quiet, -q\n" +
	"      Do not print to stdout or stderr, except for errors and warnings when provided once.\n" +
	"      Provide twice to suppress warnings as well.\n" +
	"      stdout is still redirected if --output is specified.\n" +
	"      Flag doesn't affect behaviour of download beyond not printing to terminal.\n" +
	"      \n" +
	"\n" +
	"Sessions:\n" +
	"\n" +
	"  --session SESSION_NAME_OR_PATH\n" +
	"      Create, or reuse and update a session. Within a session, custom headers,\n" +
	"      auth credential, as well as any cookies sent by the server persist between\n" +
	"      requests.\n" +
	"      \n" +
	"      Session files are stored in:\n" +
	"      \n" +
	"          [HTTPIE_CONFIG_DIR]/<HOST>/<SESSION_NAME>.json.\n" +
	"      \n" +
	"      See the following page to find out your default HTTPIE_CONFIG_DIR:\n" +
	"      \n" +
	"          https://httpie.io/docs/cli/config-file-directory\n" +
	"      \n" +
	"  --session-read-only SESSION_NAME_OR_PATH\n" +
	"      Create or read a session without updating it form the request/response\n" +
	"      exchange.\n" +
	"      \n" +
	"\n" +
	"Authentication:\n" +
	"\n" +
	"  --auth USER[:PASS] | TOKEN, -a USER[:PASS] | TOKEN\n" +
	"      For username/password based authentication mechanisms (e.g\n" +
	"      basic auth or digest auth) if only the username is provided\n" +
	"      (-a username), HTTPie will prompt for the password.\n" +
	"      \n" +
	"  --auth-type {basic,bearer,digest}, -A {basic,bearer,digest}\n" +
	"      The authentication mechanism to be used. Defaults to \"basic\".\n" +
	"      \n" +
	"      \"basic\": Basic HTTP auth\n" +
	"      \n" +
	"      \"digest\": Digest HTTP auth\n" +
	"      \n" +
	"      \"bearer\": Bearer HTTP Auth\n" +
	"      \n" +
	"  --ignore-netrc\n" +
	"      Ignore credentials from .netrc.\n" +
	"      \n" +
	"\n" +
	"Network:\n" +
	"\n" +
	"  --offline\n" +
	"      Build the request and print it but don’t actually send it.\n" +
	"      \n" +
	"  --proxy PROTOCOL:PROXY_URL\n" +
	"      String mapping protocol to the URL of the proxy\n" +
	"      (e.g. http:http://foo.bar:3128). You can specify multiple proxies with\n" +
	"      different protocols. The environment variables $ALL_PROXY, $HTTP_PROXY,\n" +
	"      and $HTTPS_proxy are supported as well.\n" +
	"      \n" +
	"  --follow, -F\n" +
	"      Follow 30x Location redirects.\n" +
	"      \n" +
	"  --max-redirects MAX_REDIRECTS\n" +
	"      By default, requests have a limit of 30 redirects (works with --follow).\n" +
	"      \n" +
	"  --max-headers MAX_HEADERS\n" +
	"      The maximum number of response headers to be read before giving up (default 0, i.e., no limit).\n" +
	"      \n" +
	"  --timeout SECONDS\n" +
	"      The connection timeout of the request in seconds.\n" +
	"      The default value is 0, i.e., there is no timeout limit.\n" +
	"      This is not a time limit on the entire response download;\n" +
	"      rather, an error is reported if the server has not issued a response for\n" +
	"      timeout seconds (more precisely, if no bytes have been received on\n" +
	"      the underlying socket for timeout seconds).\n" +
	"      \n" +
	"  --check-status\n" +
	"      By default, HTTPie exits with 0 when no network or other fatal errors\n" +
	"      occur. This flag instructs HTTPie to also check the HTTP status code and\n" +
	"      exit with an error if the status indicates one.\n" +
	"      \n" +
	"      When the server replies with a 4xx (Client Error) or 5xx (Server Error)\n" +
	"      status code, HTTPie exits with 4 or 5 respectively. If the response is a\n" +
	"      3xx (Redirect) and --follow hasn't been set, then the exit status is 3.\n" +
	"      Also an error message is written to stderr if stdout is redirected.\n" +
	"      \n" +
	"  --path-as-is\n" +
	"      Bypass dot segment (/../ or /./) URL squashing.\n" +
	"      \n" +
	"  --chunked\n" +
	"      Enable streaming via chunked transfer encoding. The Transfer-Encoding header is set to chunked.\n" +
	"      \n" +
	"\n" +
	"SSL:\n" +
	"\n" +
	"  --verify VERIFY\n" +
	"      Set to \"no\" (or \"false\") to skip checking the host's SSL certificate.\n" +
	"      Defaults to \"yes\" (\"true\"). You can also pass the path to a CA_BUNDLE file\n" +
	"      for private certs. (Or you can set the REQUESTS_CA_BUNDLE environment\n" +
	"      variable instead.)\n" +
	"      \n" +
	"  --ssl {ssl2.3,tls1,tls1.1,tls1.2}\n" +
	"      The desired protocol version to use. This will default to\n" +
	"      SSL v2.3 which will negotiate the highest protocol that both\n" +
	"      the server and your installation of OpenSSL support. Available protocols\n" +
	"      may vary depending on OpenSSL installation (only the supported ones\n" +
	"      are shown here).\n" +
	"      \n" +
	"  --ciphers CIPHERS\n" +
	"      A string in the OpenSSL cipher list format.\n" +
	"      \n" +
	"      \n" +
	"      By default, the following ciphers are used on your system:\n" +
	"      \n" +
	"      TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256\n" +
	"      \n" +
	"  --cert CERT\n" +
	"      You can specify a local cert to use as client side SSL certificate.\n" +
	"      This file may either contain both private key and certificate or you may\n" +
	"      specify --cert-key separately.\n" +
	"      \n" +
	"  --cert-key CERT_KEY\n" +
	"      The private key to use with SSL. Only needed if --cert is given and the\n" +
	"      certificate file does not contain the private key.\n" +
	"      \n" +
	"  --cert-key-pass CERT_KEY_PASS\n" +
	"      The passphrase to be used to with the given private key. Only needed if --cert-key\n" +
	"      is given and the key file requires a passphrase.\n" +
	"      If not provided, you’ll be prompted interactively.\n" +
	"      \n" +
	"\n" +
	"Troubleshooting:\n" +
	"\n" +
	"  --ignore-stdin, -I\n" +
	"      Do not attempt to read stdin\n" +
	"      \n" +
	"  --help\n" +
	"      Show this help message and exit.\n" +
	"      \n" +
	"  --manual\n" +
	"      Show the full manual.\n" +
	"      \n" +
	"  --version\n" +
	"      Show version and exit.\n" +
	"      \n" +
	"  --traceback\n" +
	"      Prints the exception traceback should one occur.\n" +
	"      \n" +
	"  --default-scheme DEFAULT_SCHEME\n" +
	"      The default scheme to use if not specified in the URL.\n" +
	"      \n" +
	"  --debug\n" +
	"      Prints the exception traceback should one occur, as well as other\n" +
	"      information useful for debugging HTTPie itself and for reporting bugs.\n" +
	"      \n" +
	"\n" +
	"For every --OPTION there is also a --no-OPTION that reverts OPTION\n" +
	"to its default value.\n" +
	"\n" +
	"Suggestions and bug reports are greatly appreciated:\n" +
	"    https://github.com/httpie/cli/issues\n"

MANUAL_TEXT ::
	"usage:\n" +
	"    http [METHOD] URL [REQUEST_ITEM ...]\n" +
	"\n" +
	"HTTPie: modern, user-friendly command-line HTTP client for the API era. \n" +
	"<https://httpie.io>\n" +
	"\n" +
	"Positional arguments:\n" +
	"  \n" +
	"  These arguments come after any flags and in the order they are listed here.\n" +
	"  Only URL is required.\n" +
	"\n" +
	"  METHOD\n" +
	"      The HTTP method to be used for the request (GET, POST, PUT, DELETE, ...).\n" +
	"      \n" +
	"      This argument can be omitted in which case HTTPie will use POST if there\n" +
	"      is some data to be sent, otherwise GET:\n" +
	"      \n" +
	"          $ http example.org               # => GET\n" +
	"          $ http example.org hello=world   # => POST\n" +
	"      \n" +
	"  URL\n" +
	"      The request URL. Scheme defaults to 'http://' if the URL\n" +
	"      does not include one. (You can override this with: \n" +
	"--default-scheme=http/https)\n" +
	"      \n" +
	"      You can also use a shorthand for localhost\n" +
	"      \n" +
	"          $ http :3000                    # => http://localhost:3000\n" +
	"          $ http :/foo                    # => http://localhost/foo\n" +
	"      \n" +
	"  REQUEST_ITEM\n" +
	"      Optional key-value pairs to be included in the request. The separator used\n" +
	"      determines the type:\n" +
	"      \n" +
	"      ':' HTTP headers:\n" +
	"      \n" +
	"          Referer:https://httpie.io  Cookie:foo=bar  User-Agent:bacon/1.0\n" +
	"      \n" +
	"      '==' URL parameters to be appended to the request URI:\n" +
	"      \n" +
	"          search==httpie\n" +
	"      \n" +
	"      '=' Data fields to be serialized into a JSON object (with --json, -j)\n" +
	"          or form data (with --form, -f):\n" +
	"      \n" +
	"          name=HTTPie  language=Python  description='CLI HTTP client'\n" +
	"      \n" +
	"      ':=' Non-string JSON data fields (only with --json, -j):\n" +
	"      \n" +
	"          awesome:=true  amount:=42  colors:='[\"red\", \"green\", \"blue\"]'\n" +
	"      \n" +
	"      '@' Form file fields (only with --form or --multipart):\n" +
	"      \n" +
	"          cv@~/Documents/CV.pdf\n" +
	"          cv@'~/Documents/CV.pdf;type=application/pdf'\n" +
	"      \n" +
	"      '=@' A data field like '=', but takes a file path and embeds its content:\n" +
	"      \n" +
	"          essay=@Documents/essay.txt\n" +
	"      \n" +
	"      ':=@' A raw JSON field like ':=', but takes a file path and embeds its \n" +
	"content:\n" +
	"      \n" +
	"          package:=@./package.json\n" +
	"      \n" +
	"      You can use a backslash to escape a colliding separator in the field name:\n" +
	"      \n" +
	"          field-name-with\\:colon=value\n" +
	"      \n" +
	"\n" +
	"Predefined content types:\n" +
	"\n" +
	"  --json, -j\n" +
	"      (default) Data items from the command line are serialized as a JSON \n" +
	"object.\n" +
	"      The Content-Type and Accept headers are set to application/json\n" +
	"      (if not specified).\n" +
	"      \n" +
	"  --form, -f\n" +
	"      Data items from the command line are serialized as form fields.\n" +
	"      \n" +
	"      The Content-Type is set to application/x-www-form-urlencoded (if not\n" +
	"      specified). The presence of any file fields results in a\n" +
	"      multipart/form-data request.\n" +
	"      \n" +
	"  --multipart\n" +
	"      Similar to --form, but always sends a multipart/form-data request (i.e., \n" +
	"even without files).\n" +
	"      \n" +
	"  --boundary BOUNDARY\n" +
	"      Specify a custom boundary string for multipart/form-data requests. Only \n" +
	"has effect only together with --form.\n" +
	"      \n" +
	"  --raw RAW\n" +
	"      This option allows you to pass raw request data without extra processing\n" +
	"      (as opposed to the structured request items syntax):\n" +
	"      \n" +
	"          $ http --raw='data' pie.dev/post\n" +
	"      \n" +
	"      You can achieve the same by piping the data via stdin:\n" +
	"      \n" +
	"          $ echo data | http pie.dev/post\n" +
	"      \n" +
	"      Or have HTTPie load the raw data from a file:\n" +
	"      \n" +
	"          $ http pie.dev/post @data.txt\n" +
	"      \n" +
	"\n" +
	"Content processing options:\n" +
	"\n" +
	"  --compress, -x\n" +
	"      Content compressed (encoded) with Deflate algorithm.\n" +
	"      The Content-Encoding header is set to deflate.\n" +
	"      \n" +
	"      Compression is skipped if it appears that compression ratio is\n" +
	"      negative. Compression can be forced by repeating the argument.\n" +
	"      \n" +
	"\n" +
	"Output processing:\n" +
	"\n" +
	"  --pretty {all,colors,format,none}\n" +
	"      Controls output processing. The value can be \"none\" to not prettify\n" +
	"      the output (default for redirected output), \"all\" to apply both colors\n" +
	"      and formatting (default for terminal output), \"colors\", or \"format\".\n" +
	"      \n" +
	"  --style STYLE, -s STYLE\n" +
	"      Output coloring style (default is \"auto\"). It can be one of:\n" +
	"      \n" +
	"              abap, algol, algol_nu, arduino, auto, autumn, borland, bw,\n" +
	"          coffee, colorful, default, dracula, emacs, friendly,\n" +
	"          friendly_grayscale, fruity, github-dark, gruvbox-dark,\n" +
	"          gruvbox-light, igor, inkpot, lightbulb, lilypond, lovelace,\n" +
	"          manni, material, monokai, murphy, native, night-owl, nord,\n" +
	"          nord-darker, one-dark, paraiso-dark, paraiso-light, pastie,\n" +
	"          perldoc, pie, pie-dark, pie-light, rainbow_dash, rrt, sas,\n" +
	"          solarized, solarized-dark, solarized-light, staroffice,\n" +
	"          stata-dark, stata-light, tango, trac, vim, vs, xcode,\n" +
	"          zenburn\n" +
	"      \n" +
	"      The \"auto\" style follows your terminal's ANSI color styles.\n" +
	"      For non-auto styles to work properly, please make sure that the\n" +
	"      $TERM environment variable is set to \"xterm-256color\" or similar\n" +
	"      (e.g., via `export TERM=xterm-256color' in your ~/.bashrc).\n" +
	"      \n" +
	"  --unsorted\n" +
	"      Disables all sorting while formatting output. It is a shortcut for:\n" +
	"      \n" +
	"          --format-options=headers.sort:false,json.sort_keys:false\n" +
	"      \n" +
	"  --sorted\n" +
	"      Re-enables all sorting options while formatting output. It is a shortcut \n" +
	"for:\n" +
	"      \n" +
	"          --format-options=headers.sort:true,json.sort_keys:true\n" +
	"      \n" +
	"  --response-charset ENCODING\n" +
	"      Override the response encoding for terminal display purposes, e.g.:\n" +
	"      \n" +
	"          --response-charset=utf8\n" +
	"          --response-charset=big5\n" +
	"      \n" +
	"  --response-mime MIME_TYPE\n" +
	"      Override the response mime type for coloring and formatting for the \n" +
	"terminal, e.g.:\n" +
	"      \n" +
	"          --response-mime=application/json\n" +
	"          --response-mime=text/xml\n" +
	"      \n" +
	"  --format-options FORMAT_OPTIONS\n" +
	"      Controls output formatting. Only relevant when formatting is enabled\n" +
	"      through (explicit or implied) --pretty=all or --pretty=format.\n" +
	"      The following are the default options:\n" +
	"      \n" +
	"          headers.sort:true\n" +
	"          json.format:true\n" +
	"          json.indent:4\n" +
	"          json.sort_keys:true\n" +
	"          xml.format:true\n" +
	"          xml.indent:2\n" +
	"      \n" +
	"      You may use this option multiple times, as well as specify multiple\n" +
	"      comma-separated options at the same time. For example, this modifies the\n" +
	"      settings to disable the sorting of JSON keys, and sets the indent size to \n" +
	"2:\n" +
	"      \n" +
	"          --format-options json.sort_keys:false,json.indent:2\n" +
	"      \n" +
	"      This is something you will typically put into your config file.\n" +
	"      \n" +
	"\n" +
	"Output options:\n" +
	"\n" +
	"  --print WHAT, -p WHAT\n" +
	"      String specifying what the output should contain:\n" +
	"      \n" +
	"          'H' request headers\n" +
	"          'B' request body\n" +
	"          'h' response headers\n" +
	"          'b' response body\n" +
	"          'm' response metadata\n" +
	"      \n" +
	"      The default behaviour is 'hb' (i.e., the response\n" +
	"      headers and body is printed), if standard output is not redirected.\n" +
	"      If the output is piped to another program or to a file, then only the\n" +
	"      response body is printed by default.\n" +
	"      \n" +
	"  --headers, -h\n" +
	"      Print only the response headers. Shortcut for --print=h.\n" +
	"      \n" +
	"  --meta, -m\n" +
	"      Print only the response metadata. Shortcut for --print=m.\n" +
	"      \n" +
	"  --body, -b\n" +
	"      Print only the response body. Shortcut for --print=b.\n" +
	"      \n" +
	"  --verbose, -v\n" +
	"      Verbose output. For the level one (with single `-v`/`--verbose`), print\n" +
	"      the whole request as well as the response. Also print any intermediary\n" +
	"      requests/responses (such as redirects). For the second level and higher,\n" +
	"      print these as well as the response metadata.\n" +
	"      \n" +
	"      Level one is a shortcut for: --all --print=BHbh\n" +
	"      Level two is a shortcut for: --all --print=BHbhm\n" +
	"      \n" +
	"  --all\n" +
	"      By default, only the final request/response is shown. Use this flag to \n" +
	"show\n" +
	"      any intermediary requests/responses as well. Intermediary requests include\n" +
	"      followed redirects (with --follow), the first unauthorized request when\n" +
	"      Digest auth is used (--auth=digest), etc.\n" +
	"      \n" +
	"  --stream, -S\n" +
	"      Always stream the response body by line, i.e., behave like `tail -f'.\n" +
	"      \n" +
	"      Without --stream and with --pretty (either set or implied),\n" +
	"      HTTPie fetches the whole response before it outputs the processed data.\n" +
	"      \n" +
	"      Set this option when you want to continuously display a prettified\n" +
	"      long-lived response, such as one from the Twitter streaming API.\n" +
	"      \n" +
	"      It is useful also without --pretty: It ensures that the output is flushed\n" +
	"      more often and in smaller chunks.\n" +
	"      \n" +
	"  --output FILE, -o FILE\n" +
	"      Save output to FILE instead of stdout. If --download is also set, then \n" +
	"only\n" +
	"      the response body is saved to FILE. Other parts of the HTTP exchange are\n" +
	"      printed to stderr.\n" +
	"      \n" +
	"  --download, -d\n" +
	"      Do not print the response body to stdout. Rather, download it and store it\n" +
	"      in a file. The filename is guessed unless specified with --output\n" +
	"      . This action is similar to the default behaviour of wget.\n" +
	"      \n" +
	"  --continue, -c\n" +
	"      Resume an interrupted download. Note that the --output option needs to be\n" +
	"      specified as well.\n" +
	"      \n" +
	"  --quiet, -q\n" +
	"      Do not print to stdout or stderr, except for errors and warnings when \n" +
	"provided once.\n" +
	"      Provide twice to suppress warnings as well.\n" +
	"      stdout is still redirected if --output is specified.\n" +
	"      Flag doesn't affect behaviour of download beyond not printing to terminal.\n" +
	"      \n" +
	"\n" +
	"Sessions:\n" +
	"\n" +
	"  --session SESSION_NAME_OR_PATH\n" +
	"      Create, or reuse and update a session. Within a session, custom headers,\n" +
	"      auth credential, as well as any cookies sent by the server persist between\n" +
	"      requests.\n" +
	"      \n" +
	"      Session files are stored in:\n" +
	"      \n" +
	"          [HTTPIE_CONFIG_DIR]/<HOST>/<SESSION_NAME>.json.\n" +
	"      \n" +
	"      See the following page to find out your default HTTPIE_CONFIG_DIR:\n" +
	"      \n" +
	"          https://httpie.io/docs/cli/config-file-directory\n" +
	"      \n" +
	"  --session-read-only SESSION_NAME_OR_PATH\n" +
	"      Create or read a session without updating it form the request/response\n" +
	"      exchange.\n" +
	"      \n" +
	"\n" +
	"Authentication:\n" +
	"\n" +
	"  --auth USER[:PASS] | TOKEN, -a USER[:PASS] | TOKEN\n" +
	"      For username/password based authentication mechanisms (e.g\n" +
	"      basic auth or digest auth) if only the username is provided\n" +
	"      (-a username), HTTPie will prompt for the password.\n" +
	"      \n" +
	"  --auth-type {basic,bearer,digest}, -A {basic,bearer,digest}\n" +
	"      The authentication mechanism to be used. Defaults to \"basic\".\n" +
	"      \n" +
	"      \"basic\": Basic HTTP auth\n" +
	"      \n" +
	"      \"digest\": Digest HTTP auth\n" +
	"      \n" +
	"      \"bearer\": Bearer HTTP Auth\n" +
	"      \n" +
	"  --ignore-netrc\n" +
	"      Ignore credentials from .netrc.\n" +
	"      \n" +
	"\n" +
	"Network:\n" +
	"\n" +
	"  --offline\n" +
	"      Build the request and print it but don’t actually send it.\n" +
	"      \n" +
	"  --proxy PROTOCOL:PROXY_URL\n" +
	"      String mapping protocol to the URL of the proxy\n" +
	"      (e.g. http:http://foo.bar:3128). You can specify multiple proxies with\n" +
	"      different protocols. The environment variables $ALL_PROXY, $HTTP_PROXY,\n" +
	"      and $HTTPS_proxy are supported as well.\n" +
	"      \n" +
	"  --follow, -F\n" +
	"      Follow 30x Location redirects.\n" +
	"      \n" +
	"  --max-redirects MAX_REDIRECTS\n" +
	"      By default, requests have a limit of 30 redirects (works with --follow).\n" +
	"      \n" +
	"  --max-headers MAX_HEADERS\n" +
	"      The maximum number of response headers to be read before giving up \n" +
	"(default 0, i.e., no limit).\n" +
	"      \n" +
	"  --timeout SECONDS\n" +
	"      The connection timeout of the request in seconds.\n" +
	"      The default value is 0, i.e., there is no timeout limit.\n" +
	"      This is not a time limit on the entire response download;\n" +
	"      rather, an error is reported if the server has not issued a response for\n" +
	"      timeout seconds (more precisely, if no bytes have been received on\n" +
	"      the underlying socket for timeout seconds).\n" +
	"      \n" +
	"  --check-status\n" +
	"      By default, HTTPie exits with 0 when no network or other fatal errors\n" +
	"      occur. This flag instructs HTTPie to also check the HTTP status code and\n" +
	"      exit with an error if the status indicates one.\n" +
	"      \n" +
	"      When the server replies with a 4xx (Client Error) or 5xx (Server Error)\n" +
	"      status code, HTTPie exits with 4 or 5 respectively. If the response is a\n" +
	"      3xx (Redirect) and --follow hasn't been set, then the exit status is 3.\n" +
	"      Also an error message is written to stderr if stdout is redirected.\n" +
	"      \n" +
	"  --path-as-is\n" +
	"      Bypass dot segment (/../ or /./) URL squashing.\n" +
	"      \n" +
	"  --chunked\n" +
	"      Enable streaming via chunked transfer encoding. The Transfer-Encoding \n" +
	"header is set to chunked.\n" +
	"      \n" +
	"\n" +
	"SSL:\n" +
	"\n" +
	"  --verify VERIFY\n" +
	"      Set to \"no\" (or \"false\") to skip checking the host's SSL certificate.\n" +
	"      Defaults to \"yes\" (\"true\"). You can also pass the path to a CA_BUNDLE file\n" +
	"      for private certs. (Or you can set the REQUESTS_CA_BUNDLE environment\n" +
	"      variable instead.)\n" +
	"      \n" +
	"  --ssl {ssl2.3,tls1,tls1.1,tls1.2}\n" +
	"      The desired protocol version to use. This will default to\n" +
	"      SSL v2.3 which will negotiate the highest protocol that both\n" +
	"      the server and your installation of OpenSSL support. Available protocols\n" +
	"      may vary depending on OpenSSL installation (only the supported ones\n" +
	"      are shown here).\n" +
	"      \n" +
	"  --ciphers CIPHERS\n" +
	"      A string in the OpenSSL cipher list format.\n" +
	"      \n" +
	"      \n" +
	"      By default, the following ciphers are used on your system:\n" +
	"      \n" +
	"      TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256\n" +
	":ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GC\n" +
	"M-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHA\n" +
	"CHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES\n" +
	"128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-\n" +
	"SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256\n" +
	"      \n" +
	"  --cert CERT\n" +
	"      You can specify a local cert to use as client side SSL certificate.\n" +
	"      This file may either contain both private key and certificate or you may\n" +
	"      specify --cert-key separately.\n" +
	"      \n" +
	"  --cert-key CERT_KEY\n" +
	"      The private key to use with SSL. Only needed if --cert is given and the\n" +
	"      certificate file does not contain the private key.\n" +
	"      \n" +
	"  --cert-key-pass CERT_KEY_PASS\n" +
	"      The passphrase to be used to with the given private key. Only needed if \n" +
	"--cert-key\n" +
	"      is given and the key file requires a passphrase.\n" +
	"      If not provided, you’ll be prompted interactively.\n" +
	"      \n" +
	"\n" +
	"Troubleshooting:\n" +
	"\n" +
	"  --ignore-stdin, -I\n" +
	"      Do not attempt to read stdin\n" +
	"      \n" +
	"  --help\n" +
	"      Show this help message and exit.\n" +
	"      \n" +
	"  --manual\n" +
	"      Show the full manual.\n" +
	"      \n" +
	"  --version\n" +
	"      Show version and exit.\n" +
	"      \n" +
	"  --traceback\n" +
	"      Prints the exception traceback should one occur.\n" +
	"      \n" +
	"  --default-scheme DEFAULT_SCHEME\n" +
	"      The default scheme to use if not specified in the URL.\n" +
	"      \n" +
	"  --debug\n" +
	"      Prints the exception traceback should one occur, as well as other\n" +
	"      information useful for debugging HTTPie itself and for reporting bugs.\n" +
	"      \n" +
	"\n" +
	"For every --OPTION there is also a --no-OPTION that reverts OPTION\n" +
	"to its default value.\n" +
	"\n" +
	"Suggestions and bug reports are greatly appreciated:\n" +
	"    https://github.com/httpie/cli/issues\n" +
	"\n"
