package cli

// Code generated by build/gen_python_digits_table.py from the
// reference's own interpreter. DO NOT EDIT.
//
// The two predicates rich's `$COLUMNS` gate runs, as code point
// ranges of the Unicode database CPython 3.11.15 was built with:
//
//   PYTHON_DIGIT_RANGES     `str.isdigit()` — the *Digit* or
//                           *Decimal* numeric type (Nd + the No
//                           digits, i.e. the superscripts);
//   PYTHON_DECIMAL_RANGES   `int()` — the *Decimal* numeric type (Nd),
//                           each range's value running from `base`
//                           upwards, one per code point.
//
// rich reads `$COLUMNS` when its `isdigit()` passes and sizes the
// console with `int(columns)`, so the first table is the gate and the
// second is the width it spells — and a code point in the first that
// is missing from the second is rich's `ValueError`
// (rich/console.py:685-694; docs/PARITY.md §3.1, t_14a26d57).
//
// Sorted by start, disjoint and inclusive, so each lookup is a binary
// search.  The decimal ranges carry the value of their first code point
// (`base`): inside a range the value steps by one, and a run of code
// points whose values restart — the mathematical alphanumerics hold five
// sets of ten — is emitted as one range per restart, which the generator
// checks.
//
//   interpreter    /home/matteo/htthor/.venv-ref/bin/python
//   python         3.11.15
//   unicodedata    14.0.0
//   isdigit()      788 code points in 81 ranges
//   int()          660 code points in 66 ranges  (the 128 left out are the digit-but-not-decimal ones)
//
// Refresh (from the reference's interpreter, which is the one whose
// database the widths are compared against):
//
//   .venv-ref/bin/python build/gen_python_digits_table.py
//   .venv-ref/bin/python build/gen_python_digits_table.py --check

@(private)
PYTHON_DIGIT_RANGES := [81][2]rune{
	{0x0030, 0x0039}, // Nd
	{0x00b2, 0x00b3}, // No
	{0x00b9, 0x00b9}, // No
	{0x0660, 0x0669}, // Nd
	{0x06f0, 0x06f9}, // Nd
	{0x07c0, 0x07c9}, // Nd
	{0x0966, 0x096f}, // Nd
	{0x09e6, 0x09ef}, // Nd
	{0x0a66, 0x0a6f}, // Nd
	{0x0ae6, 0x0aef}, // Nd
	{0x0b66, 0x0b6f}, // Nd
	{0x0be6, 0x0bef}, // Nd
	{0x0c66, 0x0c6f}, // Nd
	{0x0ce6, 0x0cef}, // Nd
	{0x0d66, 0x0d6f}, // Nd
	{0x0de6, 0x0def}, // Nd
	{0x0e50, 0x0e59}, // Nd
	{0x0ed0, 0x0ed9}, // Nd
	{0x0f20, 0x0f29}, // Nd
	{0x1040, 0x1049}, // Nd
	{0x1090, 0x1099}, // Nd
	{0x1369, 0x1371}, // No
	{0x17e0, 0x17e9}, // Nd
	{0x1810, 0x1819}, // Nd
	{0x1946, 0x194f}, // Nd
	{0x19d0, 0x19da}, // Nd
	{0x1a80, 0x1a89}, // Nd
	{0x1a90, 0x1a99}, // Nd
	{0x1b50, 0x1b59}, // Nd
	{0x1bb0, 0x1bb9}, // Nd
	{0x1c40, 0x1c49}, // Nd
	{0x1c50, 0x1c59}, // Nd
	{0x2070, 0x2070}, // No
	{0x2074, 0x2079}, // No
	{0x2080, 0x2089}, // No
	{0x2460, 0x2468}, // No
	{0x2474, 0x247c}, // No
	{0x2488, 0x2490}, // No
	{0x24ea, 0x24ea}, // No
	{0x24f5, 0x24fd}, // No
	{0x24ff, 0x24ff}, // No
	{0x2776, 0x277e}, // No
	{0x2780, 0x2788}, // No
	{0x278a, 0x2792}, // No
	{0xa620, 0xa629}, // Nd
	{0xa8d0, 0xa8d9}, // Nd
	{0xa900, 0xa909}, // Nd
	{0xa9d0, 0xa9d9}, // Nd
	{0xa9f0, 0xa9f9}, // Nd
	{0xaa50, 0xaa59}, // Nd
	{0xabf0, 0xabf9}, // Nd
	{0xff10, 0xff19}, // Nd
	{0x104a0, 0x104a9}, // Nd
	{0x10a40, 0x10a43}, // No
	{0x10d30, 0x10d39}, // Nd
	{0x10e60, 0x10e68}, // No
	{0x11052, 0x1105a}, // No
	{0x11066, 0x1106f}, // Nd
	{0x110f0, 0x110f9}, // Nd
	{0x11136, 0x1113f}, // Nd
	{0x111d0, 0x111d9}, // Nd
	{0x112f0, 0x112f9}, // Nd
	{0x11450, 0x11459}, // Nd
	{0x114d0, 0x114d9}, // Nd
	{0x11650, 0x11659}, // Nd
	{0x116c0, 0x116c9}, // Nd
	{0x11730, 0x11739}, // Nd
	{0x118e0, 0x118e9}, // Nd
	{0x11950, 0x11959}, // Nd
	{0x11c50, 0x11c59}, // Nd
	{0x11d50, 0x11d59}, // Nd
	{0x11da0, 0x11da9}, // Nd
	{0x16a60, 0x16a69}, // Nd
	{0x16ac0, 0x16ac9}, // Nd
	{0x16b50, 0x16b59}, // Nd
	{0x1d7ce, 0x1d7ff}, // Nd
	{0x1e140, 0x1e149}, // Nd
	{0x1e2f0, 0x1e2f9}, // Nd
	{0x1e950, 0x1e959}, // Nd
	{0x1f100, 0x1f10a}, // No
	{0x1fbf0, 0x1fbf9}, // Nd
}

@(private)
PYTHON_DECIMAL_RANGES := [66][3]rune{
	{0x0030, 0x0039, 0}, // Nd
	{0x0660, 0x0669, 0}, // Nd
	{0x06f0, 0x06f9, 0}, // Nd
	{0x07c0, 0x07c9, 0}, // Nd
	{0x0966, 0x096f, 0}, // Nd
	{0x09e6, 0x09ef, 0}, // Nd
	{0x0a66, 0x0a6f, 0}, // Nd
	{0x0ae6, 0x0aef, 0}, // Nd
	{0x0b66, 0x0b6f, 0}, // Nd
	{0x0be6, 0x0bef, 0}, // Nd
	{0x0c66, 0x0c6f, 0}, // Nd
	{0x0ce6, 0x0cef, 0}, // Nd
	{0x0d66, 0x0d6f, 0}, // Nd
	{0x0de6, 0x0def, 0}, // Nd
	{0x0e50, 0x0e59, 0}, // Nd
	{0x0ed0, 0x0ed9, 0}, // Nd
	{0x0f20, 0x0f29, 0}, // Nd
	{0x1040, 0x1049, 0}, // Nd
	{0x1090, 0x1099, 0}, // Nd
	{0x17e0, 0x17e9, 0}, // Nd
	{0x1810, 0x1819, 0}, // Nd
	{0x1946, 0x194f, 0}, // Nd
	{0x19d0, 0x19d9, 0}, // Nd
	{0x1a80, 0x1a89, 0}, // Nd
	{0x1a90, 0x1a99, 0}, // Nd
	{0x1b50, 0x1b59, 0}, // Nd
	{0x1bb0, 0x1bb9, 0}, // Nd
	{0x1c40, 0x1c49, 0}, // Nd
	{0x1c50, 0x1c59, 0}, // Nd
	{0xa620, 0xa629, 0}, // Nd
	{0xa8d0, 0xa8d9, 0}, // Nd
	{0xa900, 0xa909, 0}, // Nd
	{0xa9d0, 0xa9d9, 0}, // Nd
	{0xa9f0, 0xa9f9, 0}, // Nd
	{0xaa50, 0xaa59, 0}, // Nd
	{0xabf0, 0xabf9, 0}, // Nd
	{0xff10, 0xff19, 0}, // Nd
	{0x104a0, 0x104a9, 0}, // Nd
	{0x10d30, 0x10d39, 0}, // Nd
	{0x11066, 0x1106f, 0}, // Nd
	{0x110f0, 0x110f9, 0}, // Nd
	{0x11136, 0x1113f, 0}, // Nd
	{0x111d0, 0x111d9, 0}, // Nd
	{0x112f0, 0x112f9, 0}, // Nd
	{0x11450, 0x11459, 0}, // Nd
	{0x114d0, 0x114d9, 0}, // Nd
	{0x11650, 0x11659, 0}, // Nd
	{0x116c0, 0x116c9, 0}, // Nd
	{0x11730, 0x11739, 0}, // Nd
	{0x118e0, 0x118e9, 0}, // Nd
	{0x11950, 0x11959, 0}, // Nd
	{0x11c50, 0x11c59, 0}, // Nd
	{0x11d50, 0x11d59, 0}, // Nd
	{0x11da0, 0x11da9, 0}, // Nd
	{0x16a60, 0x16a69, 0}, // Nd
	{0x16ac0, 0x16ac9, 0}, // Nd
	{0x16b50, 0x16b59, 0}, // Nd
	{0x1d7ce, 0x1d7d7, 0}, // Nd
	{0x1d7d8, 0x1d7e1, 0}, // Nd
	{0x1d7e2, 0x1d7eb, 0}, // Nd
	{0x1d7ec, 0x1d7f5, 0}, // Nd
	{0x1d7f6, 0x1d7ff, 0}, // Nd
	{0x1e140, 0x1e149, 0}, // Nd
	{0x1e2f0, 0x1e2f9, 0}, // Nd
	{0x1e950, 0x1e959, 0}, // Nd
	{0x1fbf0, 0x1fbf9, 0}, // Nd
}

// PYTHON_DIGIT_BITMAP_HASH and PYTHON_DECIMAL_BITMAP_HASH are FNV-1a
// 64 over the bitmap of each range table: every code point 0x0..0x10ffff
// in order, the predicate's bit packed into a byte most-significant
// first.  The Odin suite recomputes them through the compiled predicates
// (tests/cli_test.odin:test_python_digits_match_the_generated_bitmaps),
// so the tables and `python_is_digit`/`python_int` are checked against
// the reference's database for every code point and not only for the
// ones a scenario names.
PYTHON_DIGIT_BITMAP_HASH :: u64(0x5b8d8a479b31b2c0)
PYTHON_DECIMAL_BITMAP_HASH :: u64(0x27928cea5ffa999c)
